DATA_CONTROL 	EQU P0
SELECT 		EQU P2
WRITE_DATA 	EQU P3.6
READ_DATA 	EQU P3.7

	ORG 0000H
	LJMP MAIN
	ORG 000BH
	LJMP ISR_TIMER_0

MAIN :	MOV R7,#10D
	MOV R6,#20D 
	MOV TMOD,#01H
	MOV IE,#82H
	SETB TF0
	SJMP $

ISR_TIMER_0: CLR TR0 
	DJNZ R7,SET_TIME
	DJNZ R6,LOOP
	MOV R6,#20D
	CPL IE.5
	
LOOP:	CPL PSW.5
	JB PSW.5,SWAPBIT
	MOV R7,#30D ; ------------ up
	
	JB IE.5,L_2
	MOV R3,#05H
	LJMP WRITEBIT
L_2:	MOV R3,#06H
	LJMP WRITEBIT
	
SWAPBIT:MOV R7,#10D ;------------ down
	MOV R3,#00H
WRITEBIT: MOV DATA_CONTROL,#80H
	MOV SELECT,#0FFH
	CLR WRITE_DATA
	MOV DATA_CONTROL,R3
	MOV SELECT,#0F4H
	CLR WRITE_DATA
SET_TIME: MOV TH0,#03CH
	MOV TL0,#0AFH
	SETB TR0
	RETI	
	
	END